### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by cyotee** [DMarby/humblebundle-ebook-downloader#1]
I retrieved the _simpleauth_sess from my cookie after logging into the Humble Bundle site. But I get the error:

Error using the humblebundle API, invalid session cookie?

What should I put into the auth cookie argument?

**Comment by svnk** [comment]
I got it to work. You have to escape the cookie text *including the quotes*. The simplest way to do this, is to paste it using CMD-CTRL-V. (see e.g. https://www.cnet.com/news/tips-for-the-terminal-in-os-x/ "pasting escaped text").

**Comment by DMarby** [comment]
That's awesome, great work @jlongman 👍 

Feel free to send a PR with your changes if you feel like it!

**Comment by DMarby** [comment]
I recently rewrote humblebundle-ebook-downloader, and the process for using it is now easier:
Install it using npm, and run it. This will open a browser in where you can log in to humblebundle as you would normally do on their site.
