### ISSUE TITLE
How to use the nightmare?

### ISSUE THREAD

**Issue by BattleMage** [DMarby/humblebundle-ebook-downloader#11]
I just updated from 0.0.1 to 1.0.3 and I can't figure out how to use the downloader anymore.

Nearly all parameters changed. I don't see a way to give my session cookie. Reading through the source code, the session seems to be handled by _nightmare_, but nothing happens.

I do not have a GUI, just console for my linux box.

```bash
humblebundle-ebook-downloader$ nodejs index
Starting...
Validating session...
Authenticating...
```

**Comment by DMarby** [comment]
Hi,
I've re-added the option to specify a session token by using the --auth-token option.
Please update to version 1.0.5 and it should work for you on your headless box.
