### ISSUE TITLE
After logging in via Electron the download doesn't start

### ISSUE THREAD

**Issue by tobias-p** [DMarby/humblebundle-ebook-downloader#19]
Hi, just having a new pc and tried to use your app again... Now I have the problem that after logging in with the popping up electron-window, I log in, but there nothing more happens. It doesnt matter if I run the app via powershell or cmd....

Commandline just says "Authenticating"

**Comment by Zach4422** [comment]
I am also having the same issue. Electron logs in and nothing happens.  Left it sitting hoping maybe I just needed to wait but no luck.

**Comment by AmbroseWaketon** [comment]
Same problem. Tried using 2FA to see if it was a login issue, no dice. I assume it's something to do with the website, not the program, but I could be wrong.

**Comment by DMarby** [comment]
Hi,

I've released a new version (v1.0.8) that should fix this issue, please try it out and let me know if you're still having issues :)

**Comment by bartlibert** [comment]
I still have this issue with the v1.0.8 version. Could it be related to the recaptcha?
For clarity, my login steps:
- Enter e-mail and password
- Solve a picture recaptcha (e.g. select all squares with cars)
- Enter google authenticator code
-> logged in, but nothing happens

Note: if I use the headless authentication, everything works fine.

**Comment by DMarby** [comment]
Thanks for letting me know!
It seems like the Humblebundle login flow was changed since I released 1.0.8, so it's now broken again.
I'll look into fixing it later today 👍

**Comment by DMarby** [comment]
I just released version v1.0.9 which should hopefully make it work again @bartlibert, please let me know if you have any further issues!

**Comment by bartlibert** [comment]
It works great now, thanks for the quick fix!
