### ISSUE TITLE
[IDEA] Download all option

### ISSUE THREAD

**Issue by maluramichael** [DMarby/humblebundle-ebook-downloader#3]

**Comment by jlongman** [comment]
I implemented that on my fork: https://github.com/jlongman/humblebundle-ebook-downloader

(also added using and migrating to directories named for the bundles, and creating a super simple index.html file inside, and the option to not download files (i.e. only move to bundle directories, and other stuff added a while ago)

**Comment by DMarby** [comment]
This is now added, thanks to @jlongman 👍
