### ISSUE TITLE
--all is broken on some bundles

### ISSUE THREAD

**Issue by jesdynf** [DMarby/humblebundle-ebook-downloader#8]
I have 43 bundles in my account, three of which are only available in pdf and one of which reports /no/ available formats. It would be nice if it could either by default or additional parameter gloss over the ones that don't work and focus on what does.

Thanks!

```
No downloads found matching the right format (epub) for bundle (Humble BulkyPix Mobile Bundle), available formats: (pdf)
No downloads found matching the right format (epub) for bundle (Humble Indie Bundle 11), available formats: (pdf)
No downloads found matching the right format (epub) for bundle (Humble Mobile Bundle: KEMCO X HyperDevbox), available formats: (pdf)
No downloads found matching the right format (epub) for bundle (Humble Very Positive Bundle), available formats: ()
```

**Comment by DMarby** [comment]
Hi, sorry for the slow reply!

Currently, it just outputs that warning message and continues downloading the rest of the bundles that does work, are you saying that you want it to not log the warning either?

**Comment by jesdynf** [comment]
I would swear up and down that when I ran it it reported those failed downloads and then /stopped/, but when I tried it again earlier this week everything was great, so I guess it's fine as it is. No idea what happened there -- sorry to trouble you.

**Comment by DMarby** [comment]
No worries at all, glad to hear that it's working 👍
